#!/bin/bash

PS3="Alege o optiune din meniul principal: " 
select ITEM in "Configurari pentru securitatea utilizatorilor" "Configurari ale sistemului de fisiere" "Monitorizarea sistemului" "Configurari retea" "Configurari servicii de retea" "Exit"
do
case $REPLY in 
1)./s3.sh;;
2)./s4.sh;;
3)source s5.sh;;
4)./s1.sh;;
5)./s2.sh;;
6)exit 0;;
*)echo "Varianta incorecta! Reincercati!"
esac
done
